// Slint WASM Initialization
// Generated by wasm-bindgen for Slint 1.14 showcase

import init, * as slintShowcase from '../pkg/slint_showcase_lib.js';

let slintInstance = null;

export async function initSlint() {
    try {
        await init();
        console.log('[WASM] Slint runtime initialized');
        return true;
    } catch (error) {
        console.error('[WASM] Failed to initialize Slint:', error);
        throw error;
    }
}

export function getSlintInstance() {
    return slintInstance;
}

// Export the WASM module functions for external use
export { slintShowcase };

// Auto-initialize if in browser environment
if (typeof window !== 'undefined') {
    window.addEventListener('DOMContentLoaded', async () => {
        try {
            await initSlint();
            document.dispatchEvent(new CustomEvent('slint:ready'));
        } catch (e) {
            document.dispatchEvent(new CustomEvent('slint:error', { detail: e }));
        }
    });
}
